import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={
        styles.main
      }>
        <span>
          <p className={styles.title}>Link Shortener</p>
          <p className={styles.description}>A simple link shortener</p>
        </span>
        <input className={styles.input} type="text" placeholder="Paste your link here" />
        <button className={styles.button}>Shorten</button>
      </main>
    </>
  )
}
